---
title: rogue-stack
description: A platform that deploys the maximal set of resources to run compute instances on the OCI Free Tier
locale: "en"
schemaVersion: 1.1.0
variables:
  ssh_public_key:
    title: SSH Public Key
    description: The public SSH key for the key pair used to log into compute instances via SSH
    type: oci:core:ssh:publickey
    required: true
  tenancy_ocid:
    title: Tenancy
    description: OCID of tenancy
    type: oci:identity:compartment:id
  name:
    title: Name
    description: Display name for resources
  cidr_block:
    title: VCN CIDR Block
    description: The CIDR block of the VCN created for the compute instance
  skip_init_scripts:
    title: Skip init scripts?
    description: unchecked means init scripts will run
    type: boolean
    default: false
  number_of_micros:
    title: Number of micro instances (1 or 2)
    description: choose how many micro instances you want. If you choose 1 you will get 150gb storage on Ampere otherwise 100 (p.s. no backups on micro-2) 
  use_all_storage:
    title: Use all free tier storage
    description: Always free tier gets 200 max storage space. Would you like for the Ampere instance to use all the available storage? Note - each micro instance needs 50 gb
    type: boolean
    default: false
