owner: root:root
path: /opt/traefik/data/traefik.yml
permissions: '0644'
-cloud-init-
api:
  dashboard: true
  debug: true

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: /traefik-config.yml

certificatesResolvers:
  http:
    acme:
      email: killerqueensouthfolrida@gmail.com
      storage: acme.json
      httpChallenge:
        entryPoint: http
