#cloud-config
packages_update: true
packages_upgrade: true
packages:
#  - git
#  - python3-pip
runcmd:
  # Note: Don't write files to /tmp from cloud-init use /run/somedir instead.
  # Early boot environments can race systemd-tmpfiles-clean LP: #1707222.
  - "set -ex"
  - "let(){ export -xg $1=\"$2\" ; echo \"$1='$2'\" | tee -a /home/ubuntu/.profile /root/.profile ; }"
  - "let VAULT ${vault}"
  - "let OCI_CONFIG ${oci_config}"
  - "./init_script.sh"
write_files:
- encoding: b64
  content: base64encode(${init_script})
  owner: root:root
  path: /root/init_script.sh
#  permissions: '0644'
